{"name": "test_invalid_github_url[chromium]", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.", "trace": "tests_e2e/test_basic_workflow.py:90: in test_invalid_github_url\n    home.navigate(base_url)\npage_objects/home_page.py:37: in navigate\n    self.page.wait_for_load_state(\"networkidle\")\n/usr/local/lib/python3.11/site-packages/playwright/sync_api/_generated.py:9421: in wait_for_load_state\n    self._sync(self._impl_obj.wait_for_load_state(state=state, timeout=timeout))\n/usr/local/lib/python3.11/site-packages/playwright/_impl/_page.py:491: in wait_for_load_state\n    return await self._main_frame.wait_for_load_state(**locals_to_params(locals()))\n/usr/local/lib/python3.11/site-packages/playwright/_impl/_frame.py:237: in wait_for_load_state\n    return await self._wait_for_load_state_impl(state, timeout)\n/usr/local/lib/python3.11/site-packages/playwright/_impl/_frame.py:265: in _wait_for_load_state_impl\n    await waiter.result()\nE   playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded."}, "description": "Test handling of invalid GitHub URL.", "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1747621887110, "stop": 1747621917443, "uuid": "e282c5df-3395-4988-ab68-a2ea2a848e72", "historyId": "27a0c35f4fbf8f66bfade3bbecfaa5e5", "testCaseId": "ef294bf7eef15139886ebed290aa95d6", "fullName": "tests_e2e.test_basic_workflow.TestBasicWorkflow#test_invalid_github_url", "labels": [{"name": "parentSuite", "value": "tests_e2e"}, {"name": "suite", "value": "test_basic_workflow"}, {"name": "subSuite", "value": "TestBasicWorkflow"}, {"name": "host", "value": "3bdced080a4b"}, {"name": "thread", "value": "10-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests_e2e.test_basic_workflow"}]}